### ISSUE TITLE
Please add me as a collaborator!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/cautious-lamp#1]
🌵 ⛰ 🌊

**Comment by sabajyan** [comment]
:tulip:

**Comment by syedkjaffer** [comment]
:ok:

**Comment by lorengifford** [comment]
:1st_place_medal:

**Comment by jmeng30** [comment]
👍 📙

**Comment by sdas87** [comment]
😄

**Comment by ghost** [comment]
:satellite:

**Comment by kulkarni2u** [comment]
🐎

**Comment by tgrommons** [comment]
🥇

**Comment by Gary-Holloway** [comment]
🍪

**Comment by bludesert** [comment]
:sunflower:

**Comment by steven-chou** [comment]
🐼

**Comment by Rekha-Cnc** [comment]
:sun_behind_rain_cloud:

**Comment by lmetzner** [comment]
:department_store:

**Comment by MehrnazS** [comment]
:tulip:

**Comment by butchpayroll** [comment]
:

**Comment by sivakanthn** [comment]
📟

**Comment by kidtwist29** [comment]
🤕 📦

**Comment by billyoungcc** [comment]
😀

**Comment by abizzala** [comment]
🔢

**Comment by davidjauregui** [comment]
:1st_place_medal:

**Comment by gbrower** [comment]
:dog2:

**Comment by bobshafer** [comment]
🐋

**Comment by ISalzman** [comment]
:speech_balloon:

**Comment by mkunkacnc** [comment]
:1234:

**Comment by JohnHellerud** [comment]
🚀 🚢

**Comment by RLMorrison** [comment]
:man_technologist:

**Comment by justin-silveri** [comment]
🚯

**Comment by lmetzner** [comment]
:face_with_head_bandage:

**Comment by bcadavon** [comment]
:+1:

**Comment by emilyhammer** [comment]
🍷

**Comment by githubteacher** [comment]
:tada: @sabajyan, @syedkjaffer, @lorengifford, @jmeng30, @sdas87, @marksnorman, @kulkarni2u, @tgrommons, @Gary-Holloway, @bludesert, @cnc-cchou, @RekhaSomanath, @lmetzner, @MehrnazS, @sivakanthn, @kidtwist29, @billyoungcc, @abizzala, @davidjauregui, @gbrower, @bobshafer, @ISalzman, @mkunkacnc, @JohnHellerud, @RLMorrison, @justin-silveri, @lmetzner, @butchpayroll, and @emilyhammer are now  repository collaborators. :balloon:

**Comment by justin-silveri** [comment]
🍻

**Comment by TranForsythe** [comment]
Wheeee... showing creativity by not using an emoji!

**Comment by ReneButcher** [comment]
:sos: too many emails

**Comment by jfcullen** [comment]
- :)

**Comment by JohnHellerud** [comment]
👀 🛡

**Comment by atatous** [comment]
Git is Cool

**Comment by gstaples** [comment]
🚗

**Comment by QAscoop** [comment]
🐛

**Comment by jfcullen** [comment]
👍 
🥇

**Comment by githubteacher** [comment]
:tada: @TranForsythe, @ReneButcher, @jfcullen, @atatous, @gstaples, @GroovyQA, and @jfcullen are now  repository collaborators. :balloon:

**Comment by TranForsythe** [comment]
@githubteacher Hey!

**Comment by atatous** [comment]
@githubteacher

**Comment by lmetzner** [comment]
@githubteacher

**Comment by TranForsythe** [comment]
(This is Kurt, btw - this is just my personal GitHub acct)

**Comment by QAscoop** [comment]
😭 Sorry everybody I wasn't aware that my mic was on. Muted now, thanks to @gstaples's tap on my shoulder.
