### ISSUE TITLE
recommendation

### ISSUE THREAD

**Issue by lorengifford** [githubteacher/cautious-lamp#19]
- {create a branch}
- {add a commit}
- {add files}
- {discuss}
- {merge}

**Comment by ISalzman** [comment]
You just have to be different

**Comment by lorengifford** [comment]
I just couldn't see the board. Left my glasses in the car. Typing blindly. Where's the edit button?

**Comment by TranForsythe** [comment]
Looks like a pencil, just above each post. ;)

**Comment by davidjauregui** [comment]
interesting choice loren
